trigger:
- main   # runs on changes pushed to main branch

pool:
  vmImage: 'windows-latest'
  name: "windows pool"

steps:
- task: UseJavaVersion@0
  inputs:
    versionSpec: '11'
    jdkArchitectureOption: 'x64'

- script: mvn -B clean install
  displayName: 'Run Maven Build'

